### ISSUE TITLE
Updating Price

### ISSUE THREAD

**Issue by ghost** [MenanAk47/ak47_qb_cookiesv2#1]
When trying to update the price as rank 3, the error below would happen client side:

![unknown](https://user-images.githubusercontent.com/57041193/170905547-48db18c2-fe32-4569-b736-e291eed3703a.png)

This is from the server console:

![image](https://user-images.githubusercontent.com/57041193/170905692-2a168388-5091-42e7-be85-69c38612d824.png)

**Comment by MenanAk47** [comment]
make sure you removed old tables from database before installing v2

**Comment by ghost** [comment]
Alright, I did a fresh install. Made sure that I am on duty as rank 3 and still throwing these errors in server console:

![image](https://user-images.githubusercontent.com/57041193/171018029-0e1a82bd-4727-4894-ab7d-c2d000f2e8c9.png)
